version: 2

models:
  - name: stg_dog_breeds
    description: "Staging table with cleaned and normalized dog breed data from TheDogAPI"
    columns:
      - name: breed_id
        description: "Unique breed identifier from TheDogAPI"
        tests:
          - unique
          - not_null
          
      - name: breed_name
        description: "Standardized breed name"
        tests:
          - not_null
          - unique
          
      - name: _dlt_load_id
        description: "DLT load identifier for data lineage tracking"
        
      - name: _dlt_id
        description: "DLT unique row identifier"
        tests:
          - unique
          - not_null
          
      - name: extracted_at
        description: "Timestamp when data was extracted from TheDogAPI"
        tests:
          - not_null
          
      - name: extraction_date
        description: "Date of data extraction"
        tests:
          - not_null
          
      - name: bred_for
        description: "Original purpose the breed was developed for"
        
      - name: breed_group
        description: "AKC breed group classification"
              
      - name: origin
        description: "Country or region where the breed originated"
        
      - name: country_code
        description: "ISO country code for breed origin"
        
      - name: weight_min_lbs
        description: "Minimum weight in pounds"
              
      - name: weight_max_lbs
        description: "Maximum weight in pounds"
              
      - name: weight_min_kg
        description: "Minimum weight in kilograms"
              
      - name: weight_max_kg
        description: "Maximum weight in kilograms"
              
      - name: height_min_inches
        description: "Minimum height in inches"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: 40
              
      - name: height_max_inches
        description: "Maximum height in inches"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: 40
              
      - name: height_min_cm
        description: "Minimum height in centimeters"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: 100
              
      - name: height_max_cm
        description: "Maximum height in centimeters"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: 100
              
      - name: life_span_min_years
        description: "Minimum typical lifespan in years"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1
                max_value: 25
              
      - name: life_span_max_years
        description: "Maximum typical lifespan in years"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1
                max_value: 25
              
      - name: temperament_raw
        description: "Comma-separated list of temperament traits"
        
      - name: description
        description: "Detailed breed description"
        
      - name: history
        description: "Historical information about the breed"
        
      - name: reference_image_id
        description: "TheDogAPI reference image identifier"
        
      - name: size_category
        description: "Breed size classification based on weight"
              
      - name: has_weight_data
        description: "Flag indicating if weight data is available"
        tests:
          - not_null
              
      - name: has_height_data
        description: "Flag indicating if height data is available"
        tests:
          - not_null
              
      - name: has_lifespan_data
        description: "Flag indicating if lifespan data is available"
        tests:
          - not_null
              
      - name: has_temperament_data
        description: "Flag indicating if temperament data is available"
        tests:
          - not_null

    tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "height_min_inches <= height_max_inches or height_min_inches is null or height_max_inches is null"
          config:
            severity: error
            
      - dbt_utils.expression_is_true:
          arguments:
            expression: "life_span_min_years <= life_span_max_years or life_span_min_years is null or life_span_max_years is null"
          config:
            severity: error