name: PR Tests

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    environment: testing
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: uv sync
    
    - name: Set up Google Cloud credentials
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Create dbt profiles directory
      run: mkdir -p ~/.dbt
    
    - name: Create dbt profiles.yml for CI
      run: |
        cat > ~/.dbt/profiles.yml << EOF
        dog_breed_explorer:
          target: dev
          outputs:
            dev:
              type: bigquery
              method: service-account
              project: ${{ secrets.DBT_PROJECT_ID || 'dog-breed-explorer-470208' }}
              dataset: ${{ secrets.DBT_DATASET_DEV || 'dog_explorer_dev' }}
              threads: 4
              timeout_seconds: 300
              location: europe-north2
              priority: interactive
              keyfile: ${{ steps.auth.outputs.credentials_file_path }}
        EOF
    
    - name: Run unit tests (if any exist)
      run: |
        if [ -f "tests/test_*.py" ] || [ -d "tests" ]; then
          uv run pytest tests/ -v || echo "No Python unit tests found or pytest not configured"
        else
          echo "No Python unit tests found"
        fi
    
    - name: Run dbt deps
      run: uv run dbt deps
    
    - name: Run dbt compile
      run: uv run dbt compile
    
    - name: Run dbt run (development target)
      run: uv run dbt run --target dev
    
    - name: Run dbt test
      run: uv run dbt test --target dev